name: Publish Docker image

on:
  push:
    branches:
      - main


env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/albert-api-mcp-bridge
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout MCP-Bridge repo
        uses: actions/checkout@v4
        with:
          repository: SecretiveShell/MCP-Bridge
          fetch-depth: 0
          path: mcp-bridge
      - name: Get latest tag
        id: get_hash
        run: |
          ls
          cd mcp-bridge
          LATEST_SHA=$(git log -1 --format=%H)
          echo "tag=$LATEST_SHA" >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: mcp-bridge
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
